### ISSUE TITLE
Homekit plugin fails to load in Scrypted HA 0.126.0-noble-full - Missing module source-map-support/register

### ISSUE THREAD

**Issue by resonanttoe** [koush/scrypted#1683]
**Describe the bug**
Update Scrypted in HomeAssistant to 0.126.0-noble-full 

**To Reproduce**
1. Have homekit plugin in scrypted HA,
2. Upgrade to version 0.126.0-noble-full 
3. Homekit plugin fails to load with error 

```
########################
1/9/2025, 9:02:36 AM
########################
HomeKit: loading @scrypted/homekit
HomeKit: pid 120
starting plugin @scrypted/homekit 120
node modules /data/scrypted_data/plugins/@scrypted/homekit/node20-linux-x64-20240321
plugin failed to start Error: Cannot find module 'source-map-support/register'
Require stack:
- /data/scrypted_data/plugins/@scrypted/homekit/zip/unzipped/main.nodejs.js
- /server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js
- /server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js
- /server/node_modules/@scrypted/server/dist/scrypted-main-exports.js
- /server/node_modules/@scrypted/server/dist/scrypted-main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at __non_webpack_require__ (node:internal/modules/helpers:179:18)
    at Object.call (/data/scrypted_data/plugins/@scrypted/sdk/polyfill/sourcemapsupportregister.js:1:34)
    at require (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32)
    at Object.call (/data/scrypted_data/plugins/@scrypted/homekit/src/index.ts:1:1)
    at require (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32)
    at Object.call (/data/scrypted_data/plugins/@scrypted/src/lib/Advertiser.ts:3:1)
    at r (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/scrypted_data/plugins/@scrypted/homekit/zip/unzipped/main.nodejs.js',
    '/server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main-exports.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}
plugin start/fork failed Error: Cannot find module 'source-map-support/register'
Require stack:
- /data/scrypted_data/plugins/@scrypted/homekit/zip/unzipped/main.nodejs.js
- /server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js
- /server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js
- /server/node_modules/@scrypted/server/dist/scrypted-main-exports.js
- /server/node_modules/@scrypted/server/dist/scrypted-main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at __non_webpack_require__ (node:internal/modules/helpers:179:18)
    at Object.call (/data/scrypted_data/plugins/@scrypted/sdk/polyfill/sourcemapsupportregister.js:1:34)
    at require (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32)
    at Object.call (/data/scrypted_data/plugins/@scrypted/homekit/src/index.ts:1:1)
    at require (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32)
    at Object.call (/data/scrypted_data/plugins/@scrypted/src/lib/Advertiser.ts:3:1)
    at r (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/scrypted_data/plugins/@scrypted/homekit/zip/unzipped/main.nodejs.js',
    '/server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main-exports.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}
HomeKit: Plugin failed to load. View Console for more information.
HomeKit: plugin load error Error: Cannot find module 'source-map-support/register'
Require stack:
- /data/scrypted_data/plugins/@scrypted/homekit/zip/unzipped/main.nodejs.js
- /server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js
- /server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js
- /server/node_modules/@scrypted/server/dist/scrypted-main-exports.js
- /server/node_modules/@scrypted/server/dist/scrypted-main.js
host:@scrypted/homekit
```

**Expected behavior**
Plugin loads

**Server (please complete the following information):**
 - OS: HomeAssistant OS
 - Installation Method: Addon App (Docker)

**Hardware Model (please complete the following information):**
 - Device: N/A

**Client (please complete the following information, if applicable):**
 - Software: N/A

**Additional context**

**Comment by screamer3003** [comment]
Same here

**Comment by gabriele-latino** [comment]
Same here, plus:
```
i RTSP Camera Plugin loaded @scrypted/rtsp
unhandledRejection Error: ENOENT: no such file or directory, stat '/config/www/scrypted/tmp'
    at stat (node:internal/fs/promises:1032:18)
    at Object.rmdir (node:internal/fs/promises:818:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/config/www/scrypted/tmp'
Cannot find module 'node-forge'
sharp failed to load, scrypted server may be out of date Error: Cannot find module 'sharp'
```

**Comment by KingJim1984** [comment]
Same problem here

**Comment by imc67** [comment]
Same problem here, switch to previous version does work

**Comment by ajvwhite** [comment]
+1 -- NOTE: downgrading to v1.2.61 works, but v1.2.62 shows this issue and the plugin will not load

**Comment by gabriele-latino** [comment]
unfortunately downgrade Scrypted addon version is not an easy option

**Comment by imc67** [comment]
> unfortunately downgrade Scrypted addon version is not an easy option

you can downgrade only the homekit plugin to v1.2.61 in Scripted, then it works immediately again

**Comment by archite** [comment]
Ran into same issue. For good measure I completely wiped my HomeKit config and started over for good measure. Rolling back was the only solution.

**Comment by gabriele-latino** [comment]
> you can downgrade only the homekit plugin to v1.2.61 in Scrypted, then it works immediately again

Thanks for the suggestion; for me the problem is slightly different, the errors are on the "cloud" module and its latest release is from 2/1/25; the problems appeared just after updating scrypted to 0.126.0-noble-full, so I doubt it's a plugin problem (until this morning it was working correctly)

**Comment by RGx01** [comment]
> > unfortunately downgrade Scrypted addon version is not an easy option
> 
> you can downgrade only the homekit plugin to v1.2.61 in Scrypted, then it works immediately again

@imc67 has the easiest solution. Select the second icon on the left (square split into wiggly quadrants)> select the HomeKit plugin, select a lower version (1.2.61) restart the plugin and your done.
<img width="562" alt="Screenshot 2025-01-09 at 13 00 12" src="https://github.com/user-attachments/assets/ca658317-2482-4f8b-96ea-effce79538a9" />

**Comment by gabriele-latino** [comment]
@RGx01 thanks for the suggestion but maybe I wasn't clear enough, for me the problem is due to the latest update of the Home Assistant addon "Scrypted" and not to one of its sub-plugins, for this reason downgrading Scrypted is not a one-click thing

**Comment by l45er** [comment]
Also having the same issue. Downgrading the Homekit plugin to v1.2.61 has temporarily solved it for me.

**Comment by djaytek** [comment]
same here, went back to previous version and works fine.

**Comment by DerLoco** [comment]
I downgraded Homekit plugin to v1.2.61 yesterday as well, but it was switched back automatically to the newest version over night. Is there an additional setting required to block the automatic update of the plugin? If so, how can I change this setting?

**Comment by imc67** [comment]
same here this morning however: go to add-ons > scrypted and you see there is an "update" to v0.120.0-jammy-full (actually a downgrade)

**Comment by yyax** [comment]
Same problem here

**Comment by mkz212** [comment]
> same here this morning however: go to add-ons > scrypted and you see there is an "update" to v0.120.0-jammy-full (actually a downgrade)

Same here. It showing me update that is downgrade. And need downgrade homekit plugin cause newest doesn't work.

**Comment by koush** [comment]
should be fixed

**Comment by f00kie** [comment]
The fixes do not work for me. I am on HA Scrypted v0.129.0

Downgrading the Homekit plugin to 1.2.61 is the only way this works.

**Comment by RGx01** [comment]
v0.130.1 installed with HomeKit 1.2.63 plugin. Everything now working as expected. Thanks @koush 

<img width="510" alt="Image" src="https://github.com/user-attachments/assets/b67b1672-0db9-4c42-b48c-f0d12ba66f01" />
