### ISSUE TITLE
Homekit plugin fails to load after upgrade to v0.129.0.

### ISSUE THREAD

**Issue by slyglif** [koush/scrypted#1712]
** Before You Submit**

- [x] I checked that my issue isn't already filed: [Search open issues](https://github.com/koush/scrypted/issues).
- [x] I checked the relevant camera/device and/or plugin `Log` in the `Management Console` for errors or warnings that may help identify and resolve the issue myself.

**Describe the bug**
I'm running Scrypted as a Home Assistant Addon.  After updated to v0.129.0 this morning, the Homekit plugin fails to start and the cameras are no longer available in Apple Home.

**To Reproduce**
1. Upgrade Scrypted Addon from 0.120.0 to 0.129.0
2. See Homekit plugin fails to start.
3. Try to restart to generate error log.
**Expected behavior**
Homekit plugin continues to work after upgrade

**Logs**
```
linux arm64 #1 SMP PREEMPT Mon Jan 27 11:21:24 UTC 2025
server version: 0.129.0
plugin version: @scrypted/homekit 1.2.63
full
########################
1/27/2025, 12:30:10 PM
########################
HomeKit: loading @scrypted/homekit
HomeKit: pid 199
HomeKit: @scrypted/homekit error Error: disconnect
HomeKit: plugin @scrypted/homekit unexpectedly exited, restarting in 60000ms
HomeKit: @scrypted/homekit exited null SIGKILL
HomeKit: @scrypted/homekit close
starting plugin @scrypted/homekit 199
node modules /data/scrypted_data/plugins/@scrypted/homekit/n-node-v115-linux-arm64-20250101
plugin failed to start Error: Cannot find module 'source-map-support/register'
Require stack:
- /data/scrypted_data/plugins/@scrypted/homekit/zip/unzipped/main.nodejs.js
- /server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js
- /server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js
- /server/node_modules/@scrypted/server/dist/scrypted-main-exports.js
- /server/node_modules/@scrypted/server/dist/scrypted-main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at __non_webpack_require__ (node:internal/modules/helpers:179:18)
    at Object.call (/data/scrypted_data/plugins/@scrypted/sdk/polyfill/sourcemapsupportregister.js:1:34)
    at require (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32)
    at Object.call (/data/scrypted_data/plugins/@scrypted/homekit/src/index.ts:1:1)
    at require (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32)
    at Object.call (/data/scrypted_data/plugins/@scrypted/src/lib/Advertiser.ts:3:1)
    at r (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/scrypted_data/plugins/@scrypted/homekit/zip/unzipped/main.nodejs.js',
    '/server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main-exports.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}
plugin start/fork failed Error: Cannot find module 'source-map-support/register'
Require stack:
- /data/scrypted_data/plugins/@scrypted/homekit/zip/unzipped/main.nodejs.js
- /server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js
- /server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js
- /server/node_modules/@scrypted/server/dist/scrypted-main-exports.js
- /server/node_modules/@scrypted/server/dist/scrypted-main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at __non_webpack_require__ (node:internal/modules/helpers:179:18)
    at Object.call (/data/scrypted_data/plugins/@scrypted/sdk/polyfill/sourcemapsupportregister.js:1:34)
    at require (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32)
    at Object.call (/data/scrypted_data/plugins/@scrypted/homekit/src/index.ts:1:1)
    at require (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32)
    at Object.call (/data/scrypted_data/plugins/@scrypted/src/lib/Advertiser.ts:3:1)
    at r (/data/scrypted_data/plugins/@scrypted/homekit/zip/webpack/bootstrap:19:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/scrypted_data/plugins/@scrypted/homekit/zip/unzipped/main.nodejs.js',
    '/server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main-exports.js',
    '/server/node_modules/@scrypted/server/dist/scrypted-main.js'
  ]
}
HomeKit: Plugin failed to load. View Console for more information.
HomeKit: plugin load error Error: Cannot find module 'source-map-support/register'
Require stack:
- /data/scrypted_data/plugins/@scrypted/homekit/zip/unzipped/main.nodejs.js
- /server/node_modules/@scrypted/server/dist/plugin/plugin-remote-worker.js
- /server/node_modules/@scrypted/server/dist/scrypted-plugin-main.js
- /server/node_modules/@scrypted/server/dist/scrypted-main-exports.js
- /server/node_modules/@scrypted/server/dist/scrypted-main.js
host:@scrypted/homekit
HomeKit: scheduled plugin restart cancelled, plugin was restarted by user @scrypted/homekit
```

**Server (please complete the following information):**
 - OS: HAOS 14.2
 - Installation Method: HA Addon

**Hardware Model (please complete the following information):**
 - Device: All Unifi cameras via Protect plugin

**Client (please complete the following information, if applicable):**
 - Software: Safari on MacOS

**Comment by mzac** [comment]
I have the same issue with Home assistant.  I rolled back the Homekit plugin to 1.2.61 and it works.

![Image](https://github.com/user-attachments/assets/1e30d4ae-29fe-404c-861e-966c9abeab38)

**Comment by koush** [comment]
fixed 0.130.1
